### PR TITLE
Basic Spec Listing

### PR DESCRIPTION
**Pull request by robertnperalta**
Currently entirely dummy text and links. Uses Vue router to do linking.

### CODE REVIEW

**Review by rzalog — APPROVED** [review]
Looks good.

**Review by danielskathyd — CHANGES_REQUESTED** [review]
Looks great! The only thing I'd like to see changed is more flexible margins. Users should be able to  condense their browsers and still see proper blocks for each listing.

**Comment by robertnperalta** [comment]
Should I add a method to shorten the text truncating when the window gets smaller? I tried to do something of the sort and it wasn't working out.

**Review by danielskathyd — APPROVED** [review]

**Comment by danielskathyd** [comment]
Looks great! Go ahead and merge to master. :)

**Pull request merged**
